namespace :simulate do
  task :cron => :environment do
    Simulation.simulate :from => 'rake'
  end
  
  task :invent => :environment do
    prefix = ['Clean', 'Watch', 'Visit', 'Help']
    suffix = ['My Car', 'Your Sister', 'Grandma', 'Your Room']
    p = Punishment.new
    p.name = "#{prefix[rand 4]} #{suffix[rand 4]}"
    p.description = "Autogenerated"
    p.save
  end
end
