#THIS IS A DUMMY CAPFILE.  DO NOT EXPECT IT TO WORK

namespace :whenever do
  desc "update crontab"
  task :update_crontab, :roles => :db do
    run "cd #{current_path} && whenever --update_crontab"
  end
end
